[files]
extend-exclude = [
   "src/lib/prov/pkcs11/pkcs11.h",
   "src/lib/prov/pkcs11/pkcs11t.h",
   "src/lib/prov/pkcs11/pkcs11f.h",
   "src/build-data/cc/msvc.txt",
   "src/build-data/cc/clangcl.txt",
   "doc/authors.txt",
]

[default]
extend-ignore-re = [
    "\\b[0-9A-Za-z+/]{20,80}(=|==)?\\b",
    "\\b[0-9A-Fa-f]{9,80}\\b",
]

[default.extend-words]
# This is a hack for dealing with hex
BA = "BA"
ba = "ba"

# These should be removed if possible
Probablistic = "Probablistic" # pkcs11.h typo
divisable = "divisable"       # Typo in Limbo test data

# Weird names only used in a few modules
Lik = "Lik"           # TODO(Botan4) remove when mce is removed
Projet = "Projet"     # TODO(Botan4) remove when mce is removed

# Names that typos doesn't know about
EMAC = "EMAC"
GOST = "GOST"
EDE = "EDE"
vor = "vor"

# clang-analyzer
optin = "optin"

# Abbreviations used locally, some not ideal
chello = "chello"
issu = "issu"
parm = "parm"
ser = "ser"
stuf = "stuf"
typ = "typ"
indx = "indx"

[default.extend-identifiers]
countr_zero = "countr_zero"
ARIA_FO = "ARIA_FO"
Tru64 = "Tru64"
