os: Visual Studio 2015

platform:
  - x86
  - x86_amd64

configuration:
  - Release
  - Debug

environment:
  matrix:
    - COMPILER: msvc-12.0
      MODE: --enable-shared
    - COMPILER: msvc-12.0
      MODE: --disable-shared
    - COMPILER: msvc-12.0
      MODE: --amalgamation
    - COMPILER: msvc-14.0
      MODE: --enable-shared
    - COMPILER: msvc-14.0
      MODE: --disable-shared
    - COMPILER: msvc-14.0
      MODE: --amalgamation

install:
  - if %compiler% == msvc-12.0 (
       call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %PLATFORM%
    )
  - if %compiler% == msvc-14.0 (
       call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
    )
  - cl # check compiler version
  
  - appveyor DownloadFile http://download.qt.io/official_releases/jom/jom.zip -FileName jom.zip
  - 7z e jom.zip

build_script:
  - if %configuration% == Release (
       python configure.py --cc=msvc --cpu=%PLATFORM% %MODE% --with-pkcs11
    )
  - if %configuration% == Debug (
       python configure.py --cc=msvc --cpu=%PLATFORM% %MODE% --with-pkcs11 --debug-mode
    )
  - jom -j2
  - botan-test
  - nmake install

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
